### PR TITLE
Remove duplicate

### PR DESCRIPTION
**Pull request by arichorn**

### CODE REVIEW

**Comment by arichorn** [comment]
https://dl.dropboxusercontent.com/s/i6pel7q5sukz3ms/YouTube%20v17.49.6.ipa?dl=0
also when you build uYouPlus use this.
The ipa you’re using is not decrypted.
I can tell because an ipa shouldn’t be 180MB

**Comment by arichorn** [comment]
Also I recommend using this ipa for building because the one you’re using right now is encrypted with Apple ID data. which is not work for building uYouPlus because it’ll crash the app. The one I sent above will prevent those problems for you.

**Comment by KingGamingYT** [comment]
> Also I recommend using this ipa for building because the one you’re using right now is encrypted with Apple ID data. which is not work for building uYouPlus because it’ll crash the app. The one I sent above will prevent those problems for you.

I had seen how the building guide mentioned having a decrypted ipa, and I didn’t really know how to distinguish a decrypted one to an encrypted one so I thought the one I had was perfectly fine since it passed the build process. I had obtained it through the Apple Configurator 2 cache method since I have no jailbroken devices at the moment, I really appreciate the persistent support through my stumbles!

**Comment by arichorn** [comment]
Encrypted ipas are bad and only used for jailbreak

Decrypted ipas are the best since they don’t have data inside them and can be used for sideloading & jailbreak

**Comment by arichorn** [comment]
Also I tested out your release a few minutes ago and the crashing has been resolved! 👍

**Comment by KingGamingYT** [comment]
> Also I tested out your release a few minutes ago and the crashing has been resolved! 👍

Indeed it has, though I’ve run into another issue. The app looks perfectly normal on first boot, but afterwards it’ll apply all the UI changes. I’ve gone into flags and manually toggled them on and off again to see if it would have any effect but it just doesn’t for the most part for some reason. Some things, like the channel header bar(screenshot below) are in the correct place, but most other things (watch layout, buttons, fonts, etc) are unmodified regardless of flag state.
The darker dark theme persists as well, however I manually disabled it through uYou’s settings.
A88C3860-4D89-46CB-8098-F8D4182CEBF5

**Comment by arichorn** [comment]
> > Also I tested out your release a few minutes ago and the crashing has been resolved! 👍
> 
> Indeed it has, though I’ve run into another issue. The app looks perfectly normal on first boot, but afterwards it’ll apply all the UI changes. I’ve gone into flags and manually toggled them on and off again to see if it would have any effect but it just doesn’t for the most part for some reason. Some things, like the channel header bar(screenshot below) are in the correct place, but most other things (watch layout, buttons, fonts, etc) are unmodified regardless of flag state. The darker dark theme persists as well, however I manually disabled it through uYou’s settings. A88C3860-4D89-46CB-8098-F8D4182CEBF5

It might be client side rendering which is not changeable but I’ll see what I can do

**Pull request merged**
